# Generated by Django 4.1.7 on 2023-05-01 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_hdetail_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hdetail',
            old_name='image',
            new_name='img',
        ),
    ]
