# Generated by Django 4.1.7 on 2023-05-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_rename_image_hdetail_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdetail',
            name='owner_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hdetail',
            name='owner_number',
            field=models.FloatField(null=True),
        ),
    ]
