# Generated by Django 4.1.7 on 2023-05-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_hdetail_owner_name_hdetail_owner_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdetail',
            name='owner_number',
            field=models.IntegerField(null=True),
        ),
    ]
