# Generated by Django 4.1.7 on 2023-05-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_alter_hdetail_owner_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdetail',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hdetail',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hdetail',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hdetail',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
