# Generated by Django 4.1.7 on 2023-05-07 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_post_postimage_delete_hdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='title',
        ),
        migrations.DeleteModel(
            name='Cus',
        ),
    ]
