# Generated by Django 4.1.7 on 2023-05-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0008_rename_name_post_title_delete_cus'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ownername',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
