# Generated by Django 4.1.7 on 2023-05-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_post_location_post_ownername_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
