# Generated by Django 4.1.7 on 2023-05-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_post_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
