# Generated by Django 4.1.7 on 2023-05-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0011_remove_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
