# Generated by Django 4.1.7 on 2023-05-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0012_alter_postimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
