# Generated by Django 4.1.7 on 2023-05-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
